version: '3'
services:
  mageai:
    build:
      context: .
      dockerfile: mageai.Dockerfile
    container_name: mageai
    environment:
      USER_CODE_PATH: /home/src/src
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 6789:6789 # mage-ai dashboard
      - 8080:8080 # dbt docs
    volumes:
      - ./src:/home/src/src
    restart: on-failure:5
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432" # postgres db
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: ./metabase-data/metabase.db
    ports:
      - "3000:3000" # metabase dashboard