version: 2

sources:
  - name: staging
    database: "{{ env_var('POSTGRES_DBNAME', 'public') }}"
    schema: "{{ env_var('POSTGRES_SCHEMA', 'public') }}"
    tables:
      - name: linkedin_job_positions
      - name: relocate_job_positions
      - name: glassdoor_job_positions
      - name: linkedin_job_position_details
      - name: relocate_job_position_details