column_detail_page_url = 'detail_page_url'
column_job_description = 'job_description'
column_relocation_package_options = 'relocation_package_options'
column_tags = 'tags'
column_company_info = 'company_info'
column_company_ratings = 'company_ratings'